services:
  - type: web
    name: assetflow
    env: docker
    repo: https://github.com/wesley-gomes-teixeira/teste.git
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: free
    healthCheckPath: /

    envVars:
      - key: PORT
        value: "10000"

      # PostgreSQL Render
      - key: DB_HOST
        value: dpg-d8hese4vikkc73f6mip0-a.oregon-postgres.render.com

      - key: DB_PORT
        value: "5432"

      - key: DB_USER
        value: wesley

      - key: DB_PASSWORD
        sync: false

      - key: DB_NAME
        value: assetflow_xyog

      - key: JWT_SECRET
        value: assetflow-secret-change-in-production

      - key: DISABLE_RABBITMQ
        value: "true"

      - key: INTERNAL_GATEWAY_URL
        value: http://127.0.0.1:3000

      - key: GATEWAY_BASE_URL
        value: /api

      - key: AUTH_BASE_URL
        value: /auth

      - key: USERS_SERVICE_URL
        value: http://127.0.0.1:3001

      - key: ASSETS_SERVICE_URL
        value: http://127.0.0.1:3002

      - key: TICKETS_SERVICE_URL
        value: http://127.0.0.1:3003